Repository wooga/atlas-snyk, pull requests merged in 2022-02, with the labels that each got.

#3 Add snyk download task
  build.gradle
  src/integrationTest/groovy/wooga/gradle/snyk/SnykIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/SnykPluginIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykInstallIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/snyk/SnykConventions.groovy
  src/main/groovy/wooga/gradle/snyk/SnykPlugin.groovy
  src/main/groovy/wooga/gradle/snyk/SnykPluginExtension.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/SnykInstall.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/internal/CachedGroliphantDownloader.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/internal/Downlader.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/internal/SnykDownloadAsset.groovy
Labels: add, atlas-stream

#4 Assert exit code on snyk task execution
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/TestIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/snyk/cli/SnykExitCode.groovy
  src/main/groovy/wooga/gradle/snyk/cli/SnykExitCodeResult.groovy
  src/main/groovy/wooga/gradle/snyk/cli/SnykTaskSpec.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/SnykTask.groovy
  src/test/groovy/wooga/gradle/snyk/SnykExecutionExceptionTest.groovy
Labels: improve, atlas-stream

#5 Disable task caching
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykCheckBaseIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykTaskIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/SnykTask.groovy
Labels: update, atlas-stream

#6 Add snyk runtime strategy implementation
  src/integrationTest/groovy/wooga/gradle/snyk/SnykIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/SnykPluginIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/SnykStrategyIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykCheckBaseIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/snyk/SnykConventions.groovy
  src/main/groovy/wooga/gradle/snyk/SnykPlugin.groovy
  src/main/groovy/wooga/gradle/snyk/SnykPluginExtension.groovy
  src/main/groovy/wooga/gradle/snyk/SnykStrategySpec.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/SnykTask.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/Test.groovy
  src/test/groovy/wooga/gradle/snyk/SnykPluginSpec.groovy
Labels: add, atlas-stream

#8 Improve task test setup
  build.gradle
  src/integrationTest/groovy/com/wooga/spock/extensions/snyk/Snyk.groovy
  src/integrationTest/groovy/com/wooga/spock/extensions/snyk/SnykExtension.groovy
  src/integrationTest/groovy/com/wooga/spock/extensions/snyk/interceptor/SnykFieldInterceptor.groovy
  src/integrationTest/groovy/com/wooga/spock/extensions/snyk/interceptor/SnykInterceptor.groovy
  src/integrationTest/groovy/com/wooga/spock/extensions/snyk/interceptor/SnykSharedFieldInterceptor.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/MonitorIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykCheckBaseIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykTaskIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykTestBaseIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/TestIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/snyk/cli/commands/MonitorProjectCommandSpec.groovy
  src/main/groovy/wooga/gradle/snyk/cli/commands/ProjectCommandSpec.groovy
  src/main/groovy/wooga/gradle/snyk/cli/commands/TestProjectCommandSpec.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/SnykTask.groovy
  src/test/groovy/wooga/gradle/snyk/SnykExecutionExceptionTest.groovy
Labels: improve, atlas-stream

#9 Add snykReport task
  src/integrationTest/groovy/wooga/gradle/snyk/SnykPluginIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/ReportIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykTaskIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykTestBaseIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/TestIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/snyk/SnykConventions.groovy
  src/main/groovy/wooga/gradle/snyk/SnykPlugin.groovy
  src/main/groovy/wooga/gradle/snyk/SnykPluginExtension.groovy
  src/main/groovy/wooga/gradle/snyk/report/SnykReports.groovy
  src/main/groovy/wooga/gradle/snyk/report/SnykReportsImpl.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/Report.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/SnykTask.groovy
  src/main/groovy/wooga/gradle/snyk/tasks/Test.groovy
Labels: add, atlas-stream

#10 Fix an unneeded overload in Report task
  src/main/groovy/wooga/gradle/snyk/tasks/Report.groovy
Labels: fix, atlas-stream
