Repository wooga/atlas-snyk, pull requests merged in 2022-04, with the labels that each got.

#28 Improve Closure parameter with type annotations
  src/main/groovy/wooga/gradle/snyk/SnykPluginExtension.groovy
  src/main/groovy/wooga/gradle/snyk/SnykRootPluginExtension.groovy
  src/main/groovy/wooga/gradle/snyk/SnykToHtmlPluginExtension.groovy
Labels: improve, atlas-stream

#34 Fix error in gradle option "init-script" [ATLAS-681]
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykCheckBaseIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/snyk/cli/SnykProjectSpec.groovy
  src/main/groovy/wooga/gradle/snyk/cli/options/ProjectOption.groovy
Labels: fix, atlas-stream

#35 Add snyk monitoring [ATLAS-707]
  Jenkinsfile
  build.gradle
  settings.gradle
  src/integrationTest/groovy/wooga/gradle/snyk/SnykIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/snyk/tasks/SnykTaskIntegrationSpec.groovy
Labels: add, atlas-stream
